### ISSUE TITLE
[Suggestion] Add option for convert_color to accept rgba values

### ISSUE THREAD

**Issue by Ghoulboy78** [replaceitem/scarpet-additions#2]
This would be cool and useful. tho tbh it may be added to fc soon...

**Comment by replaceitem** [comment]
Yep seems like a good idea
But i don't get why its added to carpet now considering my issue a couple months ago lol: https://github.com/gnembon/fabric-carpet/issues/374

**Comment by Ghoulboy78** [comment]
cos gnembon said so in gnembon/fabric-carpet#599: 
![image](https://user-images.githubusercontent.com/53367549/101607684-27af9d00-3a05-11eb-8027-874bd5f28d63.png)

**Comment by replaceitem** [comment]
Yeah i saw that but why now and not 5 month ago, haha, was just wondering

**Comment by replaceitem** [comment]
9ba0b52e18b87c9775f0bc94d8379e32879dd24e
