### ISSUE TITLE
[SUGGESTION] Virtual Inventory event

### ISSUE THREAD

**Issue by BisUmTo** [replaceitem/scarpet-additions#6]
`__on_player_closes_virtual_inventory(player, id)`
`__on_player_takes_item_from_virtual_inventory(player, id, slot, item_tuple)`
`__on_player_puts_item_from_virtual_inventory(player, id, slot, item_tuple)`

Replacing an item in the gui will call before "takes" and after "puts".

**Comment by replaceitem** [comment]
Virtual inventories removed in favor of https://github.com/gnembon/fabric-carpet/pull/888
