### ISSUE TITLE
[SUGGESTION]Save the contents of the virtual item bar in the world instead of keeping it in memory. 

### ISSUE THREAD

**Issue by ch-yx** [replaceitem/scarpet-additions#7]
Save the contents of the virtual item bar in the world instead of keeping it in memory. 

They can now exist **across** the worlds and unexpectedly be lost after a restart.

**Comment by replaceitem** [comment]
The virtual inventory functions in this extension will be removed anyway, once the screen handler pull request in fabric-carpet is merged. And for that, i think it doesn't make sense to store it across restarts. Most use cases don't require that, and if it needs to be stored, that can still be done with scarpet.

**Comment by ch-yx** [comment]
Yes. I do have the ability to store its contents in storage at any time and recover it on reboot. 

But I still don't understand why it should exist across worlds.

Looking forward to the day when that request is merged.
