### ISSUE TITLE
http(...) An unexpected error occurred trying to execute that command

### ISSUE THREAD

**Issue by GunnyWaffle** [replaceitem/scarpet-additions#9]
running this: `/script run http('GET', 'https://api.mojang.com/users/profiles/minecraft/gunnywaffle', 1000, 1000)`
yields this: `{name: GunnyWaffle, id: 2a98f2fc5be94ed5adf81b1790361a7e}`
Which works as expected.

However, providing a nonexistent username yields an error instead of a well formed error response.
running this: `/script run http('GET', 'https://api.mojang.com/users/profiles/minecraft/gunywaffle', 1000, 1000)`
yields this: `An unexpected error occurred trying to execute that command` in red with no further script execution.

A `try(...)` does not catch anything, with `exception` specified and there is no callstack in the server console.
I suspect that something in the mod is failing during the handling of an error response.

Here is what it looks like, with an attempt at `gunywaffle` first, then `gunnywaffle`.
![image](https://user-images.githubusercontent.com/2184320/145698249-b56ea108-ad67-4b03-8c11-da8d8f054af0.png)

**Comment by replaceitem** [comment]
Fixed in 9d6905e2f6b3ceded1881d10f5e606777561bc0b
